### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by gforcada** [plone/collective.indexing#13]
As https://github.com/plone/Products.CMFPlone/issues/1343 got merged, it would be good to make a final release of collective.indexing with the deprecation warnings.

This way, users that update to it will get the warning and not left out in the cold when they try collective.indexing on Plone 5.1

According to pypi that means: @tisto @hannosch @witsch or give plone permission to make the release and I will happily do it.

**Comment by hannosch** [comment]
I added `plone` as a maintainer, so you should be able to do a new release.

**Comment by mauritsvanrees** [comment]
If you make release 2.0b2, you should also update the version in the warning message from #12, for good measure.

**Comment by gforcada** [comment]
@mauritsvanrees thanks for the reminder I just did it. 2.0 is out!
