### ISSUE TITLE
unhashable type: 'Keyring' when adding new Plone site

### ISSUE THREAD

**Issue by kingel** [plone/collective.indexing#3]
I have a vanilla plone 4.1 buildout with 

zcml = collective.indexing:subscribers.zcml

when I add a Plone site I get this error

  Module collective.indexing.monkey, line 89, in unrestrictedSearchResults
  Module collective.indexing.queue, line 39, in processQueue
  Module collective.indexing.queue, line 151, in process
  Module collective.indexing.queue, line 125, in optimize
TypeError: unhashable type: 'Keyring'

**Comment by jensens** [comment]
outdated
